"""Add admin name for audit logs

Revision ID: 33ed2b068935
Revises: 5458d97e9fc0
Create Date: 2026-06-11 12:25:24.360463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33ed2b068935'
down_revision: Union[str, None] = '5458d97e9fc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_users', sa.Column('name', sa.String(), nullable=True))
    op.alter_column('admin_users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin_users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('admin_users', 'name')
    # ### end Alembic commands ###
