"""add_chat_composite_index

Revision ID: 4ce1bbe7fe22
Revises: a15de3ed5eb1
Create Date: 2026-05-26 11:32:04.946532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ce1bbe7fe22'
down_revision: Union[str, None] = 'a15de3ed5eb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_chat_messages_event_id_id', 'chat_messages', ['event_id', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_chat_messages_event_id_id', table_name='chat_messages')
    # ### end Alembic commands ###
