"""Add admin models and user ban fields

Revision ID: 5458d97e9fc0
Revises: 4ce1bbe7fe22
Create Date: 2026-06-11 11:39:13.418372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5458d97e9fc0'
down_revision: Union[str, None] = '4ce1bbe7fe22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_banned', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('ban_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ban_reason')
    op.drop_column('users', 'is_banned')
    # ### end Alembic commands ###
