"""add_goal_amount_to_events

Revision ID: 86b5e63ec818
Revises: e9bcae0936d5
Create Date: 2026-06-23 20:52:20.932642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86b5e63ec818'
down_revision: Union[str, None] = 'e9bcae0936d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('goal_amount', sa.Integer(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'goal_amount')
    # ### end Alembic commands ###
