"""add donation expense version receipt

Revision ID: e9bcae0936d5
Revises: 8a9d2b3c4e5f
Create Date: 2026-06-15 15:28:59.967929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9bcae0936d5'
down_revision: Union[str, None] = '8a9d2b3c4e5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donations', sa.Column('version', sa.Integer(), server_default='1', nullable=True))
    op.add_column('donations', sa.Column('is_public_entry', sa.Boolean(), server_default='0', nullable=True))
    op.add_column('expenses', sa.Column('receipt_key', sa.String(), nullable=True))
    op.add_column('expenses', sa.Column('version', sa.Integer(), server_default='1', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'version')
    op.drop_column('expenses', 'receipt_key')
    op.drop_column('donations', 'is_public_entry')
    op.drop_column('donations', 'version')
    # ### end Alembic commands ###
