"""add columns

Revision ID: f0676ca11101
Revises: f96f536ae713
Create Date: 2026-07-10 21:50:59.248412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0676ca11101'
down_revision: Union[str, None] = 'f96f536ae713'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_admin_audit_log_created_at'), 'admin_audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_messages_user_id'), 'chat_messages', ['user_id'], unique=False)
    op.create_index('idx_donations_event_collected_at', 'donations', ['event_id', 'collected_at'], unique=False)
    op.create_index('idx_donations_event_payment', 'donations', ['event_id', 'payment_received'], unique=False)
    op.create_index(op.f('ix_donations_collected_at'), 'donations', ['collected_at'], unique=False)
    op.create_index(op.f('ix_donations_collected_by'), 'donations', ['collected_by'], unique=False)
    op.create_index(op.f('ix_error_logs_created_at'), 'error_logs', ['created_at'], unique=False)
    op.create_index('idx_event_members_user_event', 'event_members', ['user_id', 'event_id'], unique=True)
    op.create_index('idx_event_members_user_role', 'event_members', ['user_id', 'role'], unique=False)
    op.create_index(op.f('ix_event_members_role'), 'event_members', ['role'], unique=False)
    op.create_index(op.f('ix_events_created_at'), 'events', ['created_at'], unique=False)
    op.create_index(op.f('ix_events_event_date'), 'events', ['event_date'], unique=False)
    op.create_index(op.f('ix_events_is_active'), 'events', ['is_active'], unique=False)
    op.create_index(op.f('ix_events_is_public'), 'events', ['is_public'], unique=False)
    op.create_index(op.f('ix_events_organizer_id'), 'events', ['organizer_id'], unique=False)
    op.create_index('idx_expenses_event_collected_at', 'expenses', ['event_id', 'collected_at'], unique=False)
    op.create_index(op.f('ix_expenses_collected_at'), 'expenses', ['collected_at'], unique=False)
    op.create_index(op.f('ix_expenses_collected_by'), 'expenses', ['collected_by'], unique=False)
    op.create_index(op.f('ix_feedback_created_at'), 'feedback', ['created_at'], unique=False)
    op.create_index(op.f('ix_feedback_status'), 'feedback', ['status'], unique=False)
    op.create_index(op.f('ix_feedback_user_id'), 'feedback', ['user_id'], unique=False)
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_full_name'), 'users', ['full_name'], unique=False)
    op.create_index(op.f('ix_users_is_banned'), 'users', ['is_banned'], unique=False)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_index('idx_watched_events_user_event', 'watched_events', ['user_id', 'event_id'], unique=True)
    op.create_index(op.f('ix_watched_events_event_id'), 'watched_events', ['event_id'], unique=False)
    op.create_index(op.f('ix_watched_events_last_viewed_at'), 'watched_events', ['last_viewed_at'], unique=False)
    op.create_index(op.f('ix_watched_events_user_id'), 'watched_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watched_events_user_id'), table_name='watched_events')
    op.drop_index(op.f('ix_watched_events_last_viewed_at'), table_name='watched_events')
    op.drop_index(op.f('ix_watched_events_event_id'), table_name='watched_events')
    op.drop_index('idx_watched_events_user_event', table_name='watched_events')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_is_banned'), table_name='users')
    op.drop_index(op.f('ix_users_full_name'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_index(op.f('ix_feedback_user_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_status'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_created_at'), table_name='feedback')
    op.drop_index(op.f('ix_expenses_collected_by'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_collected_at'), table_name='expenses')
    op.drop_index('idx_expenses_event_collected_at', table_name='expenses')
    op.drop_index(op.f('ix_events_organizer_id'), table_name='events')
    op.drop_index(op.f('ix_events_is_public'), table_name='events')
    op.drop_index(op.f('ix_events_is_active'), table_name='events')
    op.drop_index(op.f('ix_events_event_date'), table_name='events')
    op.drop_index(op.f('ix_events_created_at'), table_name='events')
    op.drop_index(op.f('ix_event_members_role'), table_name='event_members')
    op.drop_index('idx_event_members_user_role', table_name='event_members')
    op.drop_index('idx_event_members_user_event', table_name='event_members')
    op.drop_index(op.f('ix_error_logs_created_at'), table_name='error_logs')
    op.drop_index(op.f('ix_donations_collected_by'), table_name='donations')
    op.drop_index(op.f('ix_donations_collected_at'), table_name='donations')
    op.drop_index('idx_donations_event_payment', table_name='donations')
    op.drop_index('idx_donations_event_collected_at', table_name='donations')
    op.drop_index(op.f('ix_chat_messages_user_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_admin_audit_log_created_at'), table_name='admin_audit_log')
    # ### end Alembic commands ###
