"""add_payment_received_to_donations

Revision ID: f96f536ae713
Revises: 86b5e63ec818
Create Date: 2026-06-23 21:22:58.268552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f96f536ae713'
down_revision: Union[str, None] = '86b5e63ec818'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donations', sa.Column('payment_received', sa.Boolean(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('donations', 'payment_received')
    # ### end Alembic commands ###
